import random

print("Object of this game is to guess the random number generated by the system between 0 and 100.")

number = random.randint(0,100)
score = 0


while True:
    try:
        x = int(input("Enter your guess: "))
        if(x<0 or x>100):
            print("Please enter a number between 0 and 100.")
        elif(x==number):
            break
        elif(x<number):
            print("Go UP")
            score-=1
        else:
            print("Go DOWN")
            score-=1
    except ValueError:
        print("Please enter a number.")
        

print("You got the number right. Your final score is",score)
